In [1]:
import librosa
import matplotlib.pyplot as plt
import librosa.display
import os
import numpy as np
from IPython.display import Audio
import IPython.display as ipd
import wave
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
root_fp = "/home/alien/Git/DATA/ml-stuttering-events-dataset/"
CLIPS_DIR = "/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/"
df = pd.read_csv(root_fp + "SEP-28k_labels.csv")
df.head()
df.shape

(28177, 17)

In [3]:
# for d in os.listdir(CLIPS_DIR):
#     for subd in os.listdir(CLIPS_DIR + d):
#         for filename in os.listdir(CLIPS_DIR + d + "/" + subd):
#             fp = CLIPS_DIR + d + "/" + subd + "/" + filename

audio, sample_rate = librosa.load("/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/IStutterSoWhat/1/IStutterSoWhat_1_41.wav
"", res_type='kaiser_fast', sr=None)
print(sample_rate)

SyntaxError: unterminated string literal (detected at line 6) (3473101390.py, line 6)

In [4]:
audio, sample_rate = librosa.load("/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_4.wav", res_type='kaiser_fast', sr=None)

In [5]:
print(len(audio))
print(sample_rate)

48000
16000

In [9]:
Audio("/home/alien/Git/DATA/ml-stuttering-events-dataset/CLIP_DIR/MyStutteringLife/20/MyStutteringLife_20_4.wav")

In [10]:
features = {}
for d in os.listdir(CLIPS_DIR):
    for subd in os.listdir(CLIPS_DIR + d):
        for filename in os.listdir(CLIPS_DIR + d + "/" + subd):
            temp = filename[:-4]
            fp = CLIPS_DIR + d + "/" + subd + "/" + filename
            audio, sample_rate = librosa.load(fp, res_type='kaiser_fast', sr=None)
            mfccs = np.mean(librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=39).T,axis=0)
            features[temp] = mfccs
            print(temp, features[temp][0:3])

IStutterSoWhat_1_41 [-336.55563   109.50818   -26.566135]
IStutterSoWhat_1_134 [-368.05435     81.72936     -5.5951676]
IStutterSoWhat_1_91 [-307.81357    88.86299    -5.934843]
IStutterSoWhat_1_100 [-297.4501    97.5627   -24.06186]
IStutterSoWhat_1_81 [-309.89655   109.11926   -11.692066]
IStutterSoWhat_1_123 [-299.61908   105.91613   -16.535048]
IStutterSoWhat_1_13 [-328.17807   104.32346    -9.961927]
IStutterSoWhat_1_136 [-540.93616   157.55727    37.800426]
IStutterSoWhat_1_124 [-307.0806     97.166626  -19.684462]
IStutterSoWhat_1_86 [-331.65717    96.493965  -11.460839]
IStutterSoWhat_1_19 [-295.32336    99.37176   -19.336842]
IStutterSoWhat_1_61 [-282.1172    94.97656  -33.80961]
IStutterSoWhat_1_60 [-317.40793    97.052025  -22.459736]
IStutterSoWhat_1_54 [-3.6280829e+02  9.1401451e+01  3.4928542e-01]
IStutterSoWhat_1_36 [-290.2992    118.93989   -34.432693]
IStutterSoWhat_1_96 [-338.39807    108.60051     -3.1341183]
IStutterSoWhat_1_33 [-387.90692     89.66782     -6.1497564]
IStutterSoWhat_1_58 [-291.15857  111.54368  -41.60288]
IStutterSoWhat_1_35 [-340.38556    92.7901     -9.373461]
IStutterSoWhat_1_8 [-337.20407   145.64531   -14.397487]
IStutterSoWhat_1_79 [-296.5951    109.241875  -27.277472]
IStutterSoWhat_1_115 [-340.36368   107.01419   -16.902496]
IStutterSoWhat_1_88 [-255.02504   95.50537  -24.52238]
IStutterSoWhat_1_84 [-345.21716    79.55636    -4.812458]
IStutterSoWhat_1_11 [-315.0122     99.47691   -16.700077]
IStutterSoWhat_1_106 [-320.43558    95.41895   -19.171728]
IStutterSoWhat_1_71 [-360.1009     96.49737    -7.738664]
IStutterSoWhat_1_38 [-271.9744    108.392815  -38.52536 ]
IStutterSoWhat_1_103 [-355.51358    109.76479      1.8084576]
IStutterSoWhat_1_16 [-328.2951   109.62327  -19.49061]
IStutterSoWhat_1_116 [-324.14737   102.47592   -20.179523]
IStutterSoWhat_1_25 [-316.5834    103.197525  -27.139154]
IStutterSoWhat_1_128 [-301.05472   98.02568  -15.75006]
IStutterSoWhat_1_57 [-269.0749   102.08769  -35.52847]
IStutterSoWhat_1_40 [-351.88986   82.06545  -10.51883]
IStutterSoWhat_1_66 [-314.21103   103.036545  -14.697218]
IStutterSoWhat_1_94 [-346.23727   115.29917   -19.954771]
IStutterSoWhat_1_20 [-297.35718   111.32161   -31.913214]
IStutterSoWhat_1_126 [-269.31845   100.20204   -26.262367]
IStutterSoWhat_1_112 [-329.1156     98.33031   -16.208735]
IStutterSoWhat_1_7 [-301.98798   107.4801    -20.780592]
IStutterSoWhat_1_55 [-334.0963      60.642654    -0.9566163]
IStutterSoWhat_1_98 [-302.62054   121.506386  -31.475563]
IStutterSoWhat_1_118 [-307.11984    93.55998   -16.877209]
IStutterSoWhat_1_111 [-287.57242   121.32235   -24.421486]
IStutterSoWhat_1_53 [-354.3713      73.84776      1.4844888]
IStutterSoWhat_1_31 [-354.60272   116.375145  -18.50351 ]
IStutterSoWhat_1_27 [-365.89767   110.54532     9.035005]
IStutterSoWhat_1_14 [-344.78146  116.30032  -16.38251]
IStutterSoWhat_1_97 [-374.02524  117.38784   -9.83078]
IStutterSoWhat_1_127 [-290.03247    95.6032    -12.354195]
IStutterSoWhat_1_137 [-276.63086   102.498985  -36.223076]
IStutterSoWhat_1_102 [-296.42816   120.402824  -24.911577]
IStutterSoWhat_1_122 [-339.66092   100.57717   -10.145965]
IStutterSoWhat_1_125 [-305.8857   103.05191  -31.06565]
IStutterSoWhat_1_131 [-399.8969    104.60641   -10.918781]
IStutterSoWhat_1_119 [-308.45673     64.48783     -9.3218355]
IStutterSoWhat_1_51 [-336.46194    97.74041   -16.015366]
IStutterSoWhat_1_95 [-251.55188    92.884796  -38.439083]
IStutterSoWhat_1_113 [-354.64462    91.30472   -11.689983]
IStutterSoWhat_1_4 [-380.30402    83.52162    -9.284475]
IStutterSoWhat_1_49 [-317.0551     99.619865  -25.503212]
IStutterSoWhat_1_52 [-329.7823    124.16107    -3.261972]
IStutterSoWhat_1_77 [-281.19873   99.71352  -29.29383]
IStutterSoWhat_1_107 [-305.5124     64.61845    -2.152926]
IStutterSoWhat_1_135 [-251.37892    86.17029   -25.252392]
IStutterSoWhat_1_68 [-312.19873    99.33051   -19.694849]
IStutterSoWhat_1_83 [-393.4887     86.51298     4.000056]
IStutterSoWhat_1_12 [-388.87665    103.1701      -5.2432184]
IStutterSoWhat_1_24 [-331.2164    104.35101   -25.277554]
IStutterSoWhat_1_101 [-288.03998    95.52432   -20.555763]
IStutterSoWhat_1_110 [-278.32275   127.44718   -36.844746]
IStutterSoWhat_1_10 [-329.89072   98.10728  -35.14628]
IStutterSoWhat_1_34 [-335.07697  118.74992  -22.00133]
IStutterSoWhat_1_85 [-318.7619    111.49842   -13.982078]
IStutterSoWhat_1_139 [-342.57913    87.85966    -8.929934]
IStutterSoWhat_1_3 [-358.919      86.487465   -8.304633]
IStutterSoWhat_1_82 [-340.40317    87.96027   -12.027989]
IStutterSoWhat_1_30 [-312.55093     92.41842    -10.9920225]
IStutterSoWhat_1_78 [-330.69327   105.805626  -28.68483 ]
IStutterSoWhat_1_26 [-309.48694   108.84863   -24.860645]
IStutterSoWhat_1_47 [-292.0731    114.75323   -22.859222]
IStutterSoWhat_1_37 [-293.50375   101.66643   -28.958584]
IStutterSoWhat_1_87 [-258.21188  110.97275  -35.61478]
IStutterSoWhat_1_108 [-390.3251      93.66917     -0.9851984]
IStutterSoWhat_1_48 [-338.3445     80.07729    -5.778415]
IStutterSoWhat_1_59 [-264.1901   108.12183  -39.13788]
IStutterSoWhat_1_104 [-354.71677    86.35295   -10.462034]
IStutterSoWhat_1_9 [-337.3245   112.1867   -21.14059]
IStutterSoWhat_1_2 [-296.72336   107.744995  -18.767422]
IStutterSoWhat_1_76 [-285.99216    99.53808   -31.655611]
IStutterSoWhat_1_93 [-261.07364    79.00367   -27.439577]
IStutterSoWhat_1_67 [-290.21658    76.69724   -10.612275]
IStutterSoWhat_1_5 [-311.3794     92.68909   -29.464296]
IStutterSoWhat_1_46 [-293.98984   101.91265   -20.430882]
IStutterSoWhat_1_129 [-334.47037    98.80052   -14.670909]
IStutterSoWhat_1_44 [-358.24158    74.98421   -11.582502]
IStutterSoWhat_1_92 [-284.79898    94.357346  -28.431316]
IStutterSoWhat_1_63 [-274.84006  107.26871  -45.78827]
IStutterSoWhat_1_56 [-310.18552   106.95056   -30.822367]
IStutterSoWhat_1_43 [-301.7721    128.20988   -13.569178]
IStutterSoWhat_1_130 [-390.5368   103.09404  -10.11549]
IStutterSoWhat_1_0 [-305.0663     111.86065     -6.2992268]
IStutterSoWhat_1_62 [-310.80988    99.46197   -22.822472]
IStutterSoWhat_1_121 [-307.0334     87.61031   -17.096998]
IStutterSoWhat_1_132 [-334.0728     88.81037   -15.288401]
IStutterSoWhat_1_6 [-287.58093   125.20632   -30.739328]
IStutterSoWhat_1_72 [-376.85526     76.23407     -3.3584244]
IStutterSoWhat_1_73 [-401.29834    98.56979    20.621925]
IStutterSoWhat_1_22 [-328.84686   139.30702   -17.321383]
IStutterSoWhat_1_65 [-343.90887    86.380005  -12.227788]
IStutterSoWhat_1_109 [-314.60114    94.03565   -12.587912]
IStutterSoWhat_1_117 [-349.43143     98.64103      1.4704949]
IStutterSoWhat_1_99 [-273.60406   105.27073   -40.011868]
IStutterSoWhat_1_18 [-290.16733   120.34693   -37.558846]
IStutterSoWhat_1_138 [-289.21054    91.52242   -31.277737]
IStutterSoWhat_1_105 [-368.45255    83.32328    -0.484206]
IStutterSoWhat_1_42 [-304.23618   105.56493    -9.556442]
IStutterSoWhat_1_120 [-377.1287     119.191086    -0.6682456]
IStutterSoWhat_1_75 [-317.2664    104.156815  -23.19629 ]
IStutterSoWhat_1_28 [-304.63715     70.72183     -3.2190697]
IStutterSoWhat_1_39 [-289.72513    76.959366  -19.385248]
IStutterSoWhat_1_133 [-351.56674   115.269196  -19.206358]
IStutterSoWhat_1_69 [-284.69943    77.515274  -14.561907]
IStutterSoWhat_1_1 [-303.20605    90.685486  -21.596144]
IStutterSoWhat_1_70 [-363.8182     104.571495    -7.0927877]
IStutterSoWhat_1_90 [-298.31134    91.30534   -18.725645]
IStutterSoWhat_1_29 [-293.81357   100.377106  -22.035421]
IStutterSoWhat_1_74 [-349.653     107.94594    -7.074833]
IStutterSoWhat_1_50 [-368.14288    87.75533     5.718759]
IStutterSoWhat_1_114 [-324.3681    113.84455   -25.325663]
IStutterSoWhat_1_89 [-295.7763     94.572754  -16.108433]
IStutterSoWhat_1_80 [-293.9094      84.99141     -7.5232334]
IStutterSoWhat_1_23 [-334.75708   124.38487   -10.903475]
IStutterSoWhat_1_17 [-296.67715   110.44288   -32.668728]
IStutterSoWhat_1_15 [-341.17023   103.638695  -13.843623]
IStutterSoWhat_1_21 [-357.61905   116.19451   -14.319601]
IStutterSoWhat_1_32 [-319.47336   113.437035  -22.066282]
IStutterSoWhat_1_45 [-306.28513   111.8139    -24.516342]
IStutterSoWhat_1_64 [-306.96066    79.179184  -17.77617 ]
IStutterSoWhat_3_59 [-350.47516   128.9766     -8.251755]
IStutterSoWhat_3_68 [-315.29816   117.72599   -20.700272]
IStutterSoWhat_3_127 [-393.56134   119.342      24.737734]
IStutterSoWhat_3_26 [-351.98645    96.511665  -13.08543 ]
IStutterSoWhat_3_94 [-3.4311929e+02  1.0070054e+02 -2.4146676e-01]
IStutterSoWhat_3_30 [-305.65543   112.92391   -27.422297]
IStutterSoWhat_3_16 [-330.48187    97.529526  -12.922141]
IStutterSoWhat_3_98 [-273.23016    95.84641   -23.705832]
IStutterSoWhat_3_6 [-418.0665     91.051186   16.550222]
IStutterSoWhat_3_77 [-343.1366    149.71327   -13.290156]
IStutterSoWhat_3_117 [-345.80988   120.878136   -4.478386]
IStutterSoWhat_3_95 [-351.08145    86.45533     9.141222]
IStutterSoWhat_3_35 [-283.88937   113.85541   -19.817276]
IStutterSoWhat_3_104 [-311.1624   132.7743   -29.22166]
IStutterSoWhat_3_92 [-296.48688    110.1536     -10.8662195]
IStutterSoWhat_3_150 [-328.7688    103.3764    -20.292458]
IStutterSoWhat_3_34 [-288.93448    92.12817    -7.281579]
IStutterSoWhat_3_33 [-307.42487    95.56093    -4.583176]
IStutterSoWhat_3_52 [-328.0796     91.6148    -13.835538]
IStutterSoWhat_3_40 [-333.77014  108.9352    -9.09173]
IStutterSoWhat_3_97 [-246.52238   114.699715  -50.274944]
IStutterSoWhat_3_155 [-355.68134    94.163025  -20.432173]
IStutterSoWhat_3_23 [-311.683     110.127144   -7.514772]
IStutterSoWhat_3_147 [-274.63684   156.39973   -15.662123]
IStutterSoWhat_3_15 [-339.41394    105.346306     3.9255836]
IStutterSoWhat_3_85 [-320.25015   116.44332    -8.563724]
IStutterSoWhat_3_157 [-296.07794   100.98986    -8.622088]
IStutterSoWhat_3_121 [-350.83234    105.110725    -5.2839637]
IStutterSoWhat_3_9 [-315.34448  102.54067  -24.82047]
IStutterSoWhat_3_7 [-389.6348     102.20079     -3.5361974]
IStutterSoWhat_3_62 [-311.40524   118.48975   -29.441185]
IStutterSoWhat_3_67 [-268.29083  128.33391  -43.07978]
IStutterSoWhat_3_53 [-281.03275   122.841934  -35.367493]
IStutterSoWhat_3_125 [-297.13968    130.57317     -4.5947776]
IStutterSoWhat_3_55 [-354.06247    76.92373   -14.847877]
IStutterSoWhat_3_39 [-337.9654    106.04541   -16.064552]
IStutterSoWhat_3_93 [-423.73044   122.43748    17.668293]
IStutterSoWhat_3_57 [-363.44644    105.423164    -0.4212442]
IStutterSoWhat_3_143 [-334.32977   125.97932   -17.015541]
IStutterSoWhat_3_46 [-341.3741    104.78033   -12.053811]
IStutterSoWhat_3_47 [-343.07803   119.02922   -10.509573]
IStutterSoWhat_3_137 [-318.43433   114.96594   -30.114143]
IStutterSoWhat_3_28 [-313.78586  105.84349  -20.33646]
IStutterSoWhat_3_41 [-328.29727   123.2236    -27.607836]
IStutterSoWhat_3_29 [-321.02945     66.86396      5.3580136]
IStutterSoWhat_3_113 [-301.1073    132.52145     2.623968]
IStutterSoWhat_3_74 [-326.39423   105.034515  -14.955117]
IStutterSoWhat_3_21 [-346.41937   115.35207   -27.081608]
IStutterSoWhat_3_141 [-393.34607   110.940895   -2.879377]
IStutterSoWhat_3_69 [-344.14484    90.889885    3.248332]
IStutterSoWhat_3_63 [-301.1574    138.82753    -8.995847]
IStutterSoWhat_3_107 [-289.09918   120.114334  -34.920017]
IStutterSoWhat_3_100 [-296.21625   117.29918   -17.547266]
IStutterSoWhat_3_103 [-290.08917  135.0646   -38.98987]
IStutterSoWhat_3_87 [-313.3207    129.65865   -36.086166]
IStutterSoWhat_3_75 [-327.81586    100.904       -1.9984908]
IStutterSoWhat_3_152 [-298.59894    75.58071   -10.323389]
IStutterSoWhat_3_66 [-317.67206   103.61879   -18.354576]
IStutterSoWhat_3_76 [-258.15887   132.7381    -15.749239]
IStutterSoWhat_3_37 [-337.74716    110.351685    -6.0557895]
IStutterSoWhat_3_148 [-250.69267   150.65936   -18.427767]
IStutterSoWhat_3_64 [-351.79132    121.01967     -2.0454323]
IStutterSoWhat_3_32 [-289.20514   98.90892  -30.81957]
IStutterSoWhat_3_70 [-401.48862   106.91223   -10.002103]
IStutterSoWhat_3_106 [-285.81165   100.506615  -26.293264]
IStutterSoWhat_3_44 [-295.0059    139.06723     7.720637]
IStutterSoWhat_3_49 [-344.47287   118.972435  -27.925459]
IStutterSoWhat_3_158 [-373.08728    55.80667    14.459114]
IStutterSoWhat_3_124 [-255.83696  129.55789  -22.62495]
IStutterSoWhat_3_5 [-358.8519    103.85375   -23.201094]
IStutterSoWhat_3_24 [-341.90558   98.56888  -16.42391]
IStutterSoWhat_3_31 [-293.8016    101.20071   -30.172344]
IStutterSoWhat_3_50 [-307.5325   106.06926  -21.91042]
IStutterSoWhat_3_18 [-312.7314     86.375374  -18.641075]
IStutterSoWhat_3_126 [-330.73856  139.03156   17.92399]
IStutterSoWhat_3_79 [-279.12323    88.66767    15.660299]
IStutterSoWhat_3_78 [-323.41763    128.16797     -7.6713653]
IStutterSoWhat_3_1 [-352.10666     90.67435     -6.8990426]
IStutterSoWhat_3_122 [-280.64755   103.69166   -20.382175]
IStutterSoWhat_3_101 [-321.8823     96.19231    -7.732348]
IStutterSoWhat_3_10 [-298.24234    93.68348   -13.123084]
IStutterSoWhat_3_129 [-337.56256   118.85427    -4.925256]
IStutterSoWhat_3_123 [-276.5626    146.58905    -8.714834]
IStutterSoWhat_3_139 [-376.91003    124.07411      2.4608996]
IStutterSoWhat_3_115 [-388.85867    100.950386     1.3318448]
IStutterSoWhat_3_118 [-392.25238   144.36465    16.652187]
IStutterSoWhat_3_110 [-330.69788    110.760544    -7.7779913]
IStutterSoWhat_3_25 [-373.6899     85.88114   -12.566853]
IStutterSoWhat_3_154 [-295.07025   100.08573   -30.936016]
IStutterSoWhat_3_120 [-310.45853   139.80484    -9.631507]
IStutterSoWhat_3_108 [-302.08878   103.221085  -21.949062]
IStutterSoWhat_3_114 [-315.91055   122.485374   20.855328]
IStutterSoWhat_3_131 [-325.07718   129.56766   -10.577533]
IStutterSoWhat_3_135 [-268.05096   147.4593    -15.541698]
IStutterSoWhat_3_90 [-333.2006   111.74843   -9.90859]
IStutterSoWhat_3_133 [-270.78094   120.21502   -23.815336]
IStutterSoWhat_3_112 [-286.19763   161.17598   -13.175349]
IStutterSoWhat_3_19 [-335.50433   107.96332   -16.203575]
IStutterSoWhat_3_56 [-271.3289    123.693695  -33.304924]
IStutterSoWhat_3_134 [-249.44473   132.48961   -23.079662]
IStutterSoWhat_3_45 [-350.546     135.69426    17.500275]
IStutterSoWhat_3_14 [-328.34216   141.42784    -6.824031]
IStutterSoWhat_3_84 [-331.0771    112.48032     3.202679]
IStutterSoWhat_3_144 [-260.96088  136.06438  -21.90492]
IStutterSoWhat_3_22 [-372.0271    101.57      -14.327294]
IStutterSoWhat_3_81 [-324.374      131.82385      1.7860694]
IStutterSoWhat_3_17 [-305.9939     87.24584   -19.554739]
IStutterSoWhat_3_132 [-305.87704   112.61426   -22.667969]
IStutterSoWhat_3_65 [-370.6414     83.53743    -5.804666]
IStutterSoWhat_3_105 [-300.23538    88.9068    -16.471176]
IStutterSoWhat_3_140 [-331.3534    117.82695   -23.875156]
IStutterSoWhat_3_60 [-330.77667   109.20657    14.101425]
IStutterSoWhat_3_8 [-286.44418  120.50133  -34.30902]
IStutterSoWhat_3_130 [-287.35602   134.70792   -22.232897]
IStutterSoWhat_3_109 [-397.96786    118.32008      2.4255085]
IStutterSoWhat_3_116 [-353.1922     113.82895     -3.8122475]
IStutterSoWhat_3_142 [-392.7229    139.50186     9.127772]
IStutterSoWhat_3_91 [-418.1173     83.77752    -8.956703]
IStutterSoWhat_3_61 [-338.78586   122.78111   -24.075775]
IStutterSoWhat_3_13 [-280.97595   121.312996   -5.216684]
IStutterSoWhat_3_36 [-281.41144    97.32407   -25.436157]
IStutterSoWhat_3_54 [-459.66785   131.11908    20.592592]
IStutterSoWhat_3_136 [-325.23456    116.63566     -2.9431481]
IStutterSoWhat_3_12 [-268.31036    131.33032     -3.7097492]
IStutterSoWhat_3_156 [-334.17606     96.472824    -4.8050685]
IStutterSoWhat_3_102 [-335.66284    102.2836      -5.7921824]
IStutterSoWhat_3_11 [-291.9028    126.51368   -27.499338]
IStutterSoWhat_3_138 [-339.28      104.83659   -15.459599]
IStutterSoWhat_3_38 [-328.25024    80.063545    5.050808]
IStutterSoWhat_3_146 [-227.7063    149.66042   -32.671318]
IStutterSoWhat_3_72 [-348.247     129.8257      7.310412]
IStutterSoWhat_3_99 [-387.876       94.79143     -7.8424454]
IStutterSoWhat_3_71 [-399.37463     93.32016      1.7112553]
IStutterSoWhat_3_149 [-285.99503    108.9149      -7.7725916]
IStutterSoWhat_3_51 [-330.47897    69.252426  -12.102981]
IStutterSoWhat_3_83 [-356.4475     119.736565    -5.4559684]
IStutterSoWhat_3_27 [-363.50858    89.3746     -7.549166]
IStutterSoWhat_3_96 [-305.7992     98.53415    -8.749432]
IStutterSoWhat_3_4 [-4.2577850e+02  1.2307444e+02 -2.2197285e-01]
IStutterSoWhat_3_42 [-335.77472  120.57937  -16.87198]
IStutterSoWhat_3_0 [-367.93616    107.24547      7.3478675]
IStutterSoWhat_3_119 [-284.24573    146.58176     -3.4112906]
IStutterSoWhat_3_58 [-296.4094   127.86357  -30.40683]
IStutterSoWhat_3_20 [-409.5184    133.709      -8.296932]
IStutterSoWhat_3_153 [-311.2676  103.7244  -19.9221]
IStutterSoWhat_3_3 [-326.9041    103.46734   -16.135517]
IStutterSoWhat_3_111 [-267.30426   118.55064    -9.693601]
IStutterSoWhat_3_128 [-293.8196    128.98293   -30.624475]
IStutterSoWhat_3_48 [-293.3122   116.04338  -23.64219]
IStutterSoWhat_3_86 [-296.6742    122.78889   -10.687266]
IStutterSoWhat_3_2 [-341.98373    95.48349   -18.891563]
IStutterSoWhat_3_73 [-311.72745     97.971115    -3.6132016]
IStutterSoWhat_3_43 [-274.11282   137.58615   -30.879942]
IStutterSoWhat_3_151 [-282.32053    84.8442    -29.733074]
IStutterSoWhat_3_88 [-330.1058   101.88892  -15.35944]
IStutterSoWhat_3_82 [-375.78644    120.606255    -1.4190993]
IStutterSoWhat_3_80 [-296.5092    117.46123     8.220935]
IStutterSoWhat_3_145 [-251.32817   145.33488   -13.532669]
IStutterSoWhat_3_89 [-325.07788  108.82876  -20.75043]
IStutterSoWhat_4_78 [-311.96658   111.8206    -14.138455]
IStutterSoWhat_4_132 [-382.62906   107.39568    -3.314052]
IStutterSoWhat_4_104 [-334.95557   143.85791    15.774449]
IStutterSoWhat_4_85 [-326.75836   126.52017    15.951964]
IStutterSoWhat_4_130 [-324.84567    86.80028   -12.115561]
IStutterSoWhat_4_35 [-309.60428   137.6186     16.044853]
IStutterSoWhat_4_30 [-333.22855   126.570854   11.09725 ]
IStutterSoWhat_4_62 [-318.00977  106.50323  -12.23133]
IStutterSoWhat_4_157 [-307.27115     72.985054    -6.7116075]
IStutterSoWhat_4_101 [-300.80023   128.68605    17.319529]
IStutterSoWhat_4_102 [-299.4073    120.63571    26.600729]
IStutterSoWhat_4_131 [-307.15997     98.601166    -6.9055624]
IStutterSoWhat_4_143 [-304.15228   100.56588   -10.162213]
IStutterSoWhat_4_88 [-323.8916    93.81911   31.36132]
IStutterSoWhat_4_166 [-305.62317    86.867294  -25.44777 ]
IStutterSoWhat_4_125 [-320.17242   101.8788    -13.731331]
IStutterSoWhat_4_51 [-319.80432   134.06749    15.455545]
IStutterSoWhat_4_139 [-258.80695    91.45012   -11.752169]
IStutterSoWhat_4_109 [-325.0145    139.94614     8.449632]
IStutterSoWhat_4_24 [-342.2861     143.66432     10.6304865]
IStutterSoWhat_4_5 [-320.44214   104.76306   -39.776108]
IStutterSoWhat_4_83 [-348.0677    119.97352    22.730972]
IStutterSoWhat_4_16 [-333.57608    129.20305      7.5751095]
IStutterSoWhat_4_74 [-296.92844  118.9661    32.05002]
IStutterSoWhat_4_123 [-376.78583     97.22187      1.6309024]
IStutterSoWhat_4_165 [-337.5402    108.45873   -21.663965]
IStutterSoWhat_4_72 [-283.03333  133.14906   26.04824]
IStutterSoWhat_4_108 [-354.74744   145.99951     8.926466]
IStutterSoWhat_4_43 [-263.31802   107.4186    -36.828697]
IStutterSoWhat_4_69 [-338.54828   144.52142    12.808898]
IStutterSoWhat_4_163 [-316.59048   105.35164   -16.415333]
IStutterSoWhat_4_13 [-351.0973    127.91871    13.867619]
IStutterSoWhat_4_110 [-338.56424  134.26045   21.19171]
IStutterSoWhat_4_39 [-320.81534  130.89941   18.39225]
IStutterSoWhat_4_93 [-322.7862    133.26254    17.705906]
IStutterSoWhat_4_98 [-329.40192  138.01155   18.10101]
IStutterSoWhat_4_99 [-327.53384   125.50368    21.754778]
IStutterSoWhat_4_107 [-315.27548   129.88995    13.445593]
IStutterSoWhat_4_116 [-332.16998     91.14293     -7.7409844]
IStutterSoWhat_4_133 [-375.72165   120.05678    -8.606019]
IStutterSoWhat_4_136 [-339.47897   107.612045  -13.484449]
IStutterSoWhat_4_100 [-322.7853    134.8147     19.790052]
IStutterSoWhat_4_57 [-325.03955   139.57562    16.236961]

In [11]:
print(len(features))
print(len(features['HeStutters_1_1']))
print(features['HeStutters_1_1'])

21856
39
[-4.3998596e+02  8.8102333e+01 -1.9981874e+00  3.3194103e+01
  5.1922268e-01 -6.4415989e+00 -2.1857227e+01 -4.3765087e+00
 -2.1993494e+01 -7.5185838e+00 -1.7888243e+01 -5.1863441e+00
 -6.2575808e+00 -1.4505777e+01  3.0002469e-01 -1.0869891e+01
 -7.2807229e-01 -6.9588623e+00 -2.3852012e+00 -3.9837780e+00
 -1.1165423e+00 -2.1915677e+00 -3.7827320e+00 -2.5932920e+00
 -3.5841548e+00 -6.6944081e-01 -4.8956537e+00 -9.8046207e-01
 -3.0367424e+00 -1.3212522e+00 -3.7078540e+00 -1.9546180e+00
 -2.4988875e+00 -3.6508338e+00 -2.7487745e+00 -3.1710665e+00
 -2.7716229e+00 -3.7814844e+00 -1.1346221e+00]

# mfcc features dataset

In [12]:
df_features = pd.DataFrame.from_dict(features)
df_features = df_features.transpose()
df_features

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
IStutterSoWhat_1_41,-336.555634,109.508179,-26.566135,29.132792,-2.612384,13.964765,-4.747061,-10.869653,-9.985801,1.656807,...,-0.180334,-0.331044,0.983381,-0.469176,-0.761282,0.152868,-2.450095,-2.527094,-1.104110,-1.137267
IStutterSoWhat_1_134,-368.054352,81.729362,-5.595168,11.588620,1.515548,21.053503,2.168665,-3.381476,-3.864866,-2.001917,...,4.590621,4.768090,5.220447,5.128517,6.109529,5.229824,2.631895,2.375573,0.607299,2.467714
IStutterSoWhat_1_91,-307.813568,88.862991,-5.934843,27.808754,-1.034236,20.686192,1.663162,-7.051512,-13.588875,-9.944215,...,-0.101414,-2.210516,2.478186,-2.038970,-0.468538,-0.851471,3.323346,2.677554,2.749101,3.670835
IStutterSoWhat_1_100,-297.450104,97.562698,-24.061859,35.173100,3.828866,14.398861,-2.087997,-8.942782,-11.547944,-12.029325,...,-1.020632,-1.260126,1.445629,-2.504155,0.152286,-1.214500,-0.670810,0.810952,-1.247550,1.720245
IStutterSoWhat_1_81,-309.896545,109.119263,-11.692066,27.686235,-13.686394,14.858957,3.239554,-15.508041,-18.927382,-9.252060,...,2.566494,-1.349176,1.186738,-0.931486,-3.613741,-2.333425,0.893552,-3.177019,-3.396168,-1.742824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MyStutteringLife_17_24,-362.988190,94.855507,-6.502656,29.474913,-17.147413,-13.703700,-22.483486,-26.712208,-11.004487,-16.098314,...,-1.742022,1.884807,3.649453,2.408923,-1.138234,-1.821348,1.152534,0.094795,-0.712158,-0.317898
MyStutteringLife_17_21,-421.284729,72.423706,-13.014243,32.113201,-23.712561,-19.454187,-9.508771,-20.479137,-12.363506,-1.501922,...,0.576001,2.775250,1.266903,-1.652585,0.983812,0.174276,0.297633,0.799410,-3.804478,-1.042573
MyStutteringLife_17_12,-396.949890,51.924320,0.791150,26.625509,-15.318913,-6.733788,-15.506890,-14.703095,-9.645512,1.013115,...,0.602919,1.817915,2.295668,1.643318,-0.235362,-1.923930,-0.548312,-1.079760,0.843451,0.040082
MyStutteringLife_17_18,-371.221313,62.781338,-11.562328,26.399954,-8.609015,-2.140243,-2.747787,-3.306388,-8.191533,3.270486,...,-0.551212,-0.255060,0.238226,-1.827243,-0.631921,-2.694419,-0.300344,-1.857425,-1.054838,0.471497
MyStutteringLife_17_34,-400.839020,39.196194,2.447978,45.856621,-0.664329,-7.624115,-7.610217,-8.090629,-10.672312,-2.991638,...,-1.249962,-2.077747,-0.382612,-2.647896,-1.174062,-1.820649,0.216157,-1.233376,-0.988283,-1.925266

In [13]:
df_features = df_features.reset_index()
df_features

,index,0,1,2,3,4,5,6,7,8,...,29,30,31,32,33,34,35,36,37,38
0,IStutterSoWhat_1_41,-336.555634,109.508179,-26.566135,29.132792,-2.612384,13.964765,-4.747061,-10.869653,-9.985801,...,-0.180334,-0.331044,0.983381,-0.469176,-0.761282,0.152868,-2.450095,-2.527094,-1.104110,-1.137267
1,IStutterSoWhat_1_134,-368.054352,81.729362,-5.595168,11.588620,1.515548,21.053503,2.168665,-3.381476,-3.864866,...,4.590621,4.768090,5.220447,5.128517,6.109529,5.229824,2.631895,2.375573,0.607299,2.467714
2,IStutterSoWhat_1_91,-307.813568,88.862991,-5.934843,27.808754,-1.034236,20.686192,1.663162,-7.051512,-13.588875,...,-0.101414,-2.210516,2.478186,-2.038970,-0.468538,-0.851471,3.323346,2.677554,2.749101,3.670835
3,IStutterSoWhat_1_100,-297.450104,97.562698,-24.061859,35.173100,3.828866,14.398861,-2.087997,-8.942782,-11.547944,...,-1.020632,-1.260126,1.445629,-2.504155,0.152286,-1.214500,-0.670810,0.810952,-1.247550,1.720245
4,IStutterSoWhat_1_81,-309.896545,109.119263,-11.692066,27.686235,-13.686394,14.858957,3.239554,-15.508041,-18.927382,...,2.566494,-1.349176,1.186738,-0.931486,-3.613741,-2.333425,0.893552,-3.177019,-3.396168,-1.742824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21851,MyStutteringLife_17_24,-362.988190,94.855507,-6.502656,29.474913,-17.147413,-13.703700,-22.483486,-26.712208,-11.004487,...,-1.742022,1.884807,3.649453,2.408923,-1.138234,-1.821348,1.152534,0.094795,-0.712158,-0.317898
21852,MyStutteringLife_17_21,-421.284729,72.423706,-13.014243,32.113201,-23.712561,-19.454187,-9.508771,-20.479137,-12.363506,...,0.576001,2.775250,1.266903,-1.652585,0.983812,0.174276,0.297633,0.799410,-3.804478,-1.042573
21853,MyStutteringLife_17_12,-396.949890,51.924320,0.791150,26.625509,-15.318913,-6.733788,-15.506890,-14.703095,-9.645512,...,0.602919,1.817915,2.295668,1.643318,-0.235362,-1.923930,-0.548312,-1.079760,0.843451,0.040082
21854,MyStutteringLife_17_18,-371.221313,62.781338,-11.562328,26.399954,-8.609015,-2.140243,-2.747787,-3.306388,-8.191533,...,-0.551212,-0.255060,0.238226,-1.827243,-0.631921,-2.694419,-0.300344,-1.857425,-1.054838,0.471497
21855,MyStutteringLife_17_34,-400.839020,39.196194,2.447978,45.856621,-0.664329,-7.624115,-7.610217,-8.090629,-10.672312,...,-1.249962,-2.077747,-0.382612,-2.647896,-1.174062,-1.820649,0.216157,-1.233376,-0.988283,-1.925266

In [14]:
df_features = df_features.sort_values(by='index')
df_features

,index,0,1,2,3,4,5,6,7,8,...,29,30,31,32,33,34,35,36,37,38
15611,HVSA_0_0,-672.897095,42.572784,-9.060439,17.092854,5.601506,11.969574,5.087627,1.287422,-1.221630,...,-2.856751,-3.665334,-0.368020,-5.483552,-3.434580,-1.979492,-2.022152,-0.937069,0.002662,-2.381591
15521,HVSA_0_1,-463.573730,69.182426,-18.914116,22.859167,0.735867,-7.253482,-7.202471,-5.319007,-5.854908,...,-7.792398,-9.402816,-6.964743,-5.560274,-5.928011,-6.585182,-5.301041,-4.754488,-5.721908,-8.970046
15599,HVSA_0_10,-452.379944,58.461617,-26.529619,10.806691,1.040473,-11.684329,-15.975926,-17.110899,-8.533467,...,-5.176428,-3.543585,-4.472883,-2.353557,1.883047,-0.825696,-3.325481,2.212896,-4.497185,-7.248011
15621,HVSA_0_100,-454.134918,85.565826,-16.623894,23.212719,-7.808586,-7.204660,-8.445378,-17.406126,-16.752789,...,-4.534226,-5.633986,-0.189009,-2.829734,-5.591987,-2.570790,-4.265398,-1.526478,-1.496358,-6.113244
15631,HVSA_0_101,-419.757965,73.650085,-20.263416,30.691788,-5.919299,-15.747584,-17.799961,-13.380462,-10.132165,...,-4.724228,-6.154249,-2.757484,-4.379042,-3.424964,-2.619114,-3.643760,1.918766,-5.222338,-9.505955
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7334,WomenWhoStutter_9_5,-331.060883,8.423851,-32.912979,25.618399,-23.380960,2.367096,-14.927188,-5.307941,0.028746,...,1.926433,-2.305741,1.709073,0.266926,2.327720,-2.078656,-2.214721,-1.796524,1.960576,0.512515
7339,WomenWhoStutter_9_6,-287.171539,24.612055,11.593957,-2.373049,-19.041893,1.381284,-8.410904,-6.094374,-21.232731,...,1.157626,1.489891,-1.526303,-4.642986,-2.262572,-2.588369,2.589427,-5.378926,0.691114,-3.360295
7357,WomenWhoStutter_9_7,-284.419769,69.935936,4.447401,25.512430,-23.518784,-3.872571,2.403355,-14.279772,-22.612999,...,1.685291,-3.814619,1.026565,-3.971704,1.371947,1.164272,2.777372,-0.703542,-1.983613,-1.159616
7340,WomenWhoStutter_9_8,-359.677887,48.367851,14.129713,3.370583,-19.779791,1.081605,-1.616947,-4.654747,-21.594097,...,4.271441,1.339565,-1.568165,-2.710129,1.628097,-2.416452,2.993908,0.311044,-1.634658,-3.653098
7344,WomenWhoStutter_9_9,-308.420288,43.304848,4.558290,25.408195,-5.581814,-15.347582,-3.209874,-7.895386,-15.488366,...,1.119454,3.923148,-0.920379,-0.061525,1.307001,-3.842120,-0.719028,-5.158088,-0.348154,-4.080893

In [15]:
df_features.rename(columns = {'index':'Name'}, inplace = True)
df_features

,Name,0,1,2,3,4,5,6,7,8,...,29,30,31,32,33,34,35,36,37,38
15611,HVSA_0_0,-672.897095,42.572784,-9.060439,17.092854,5.601506,11.969574,5.087627,1.287422,-1.221630,...,-2.856751,-3.665334,-0.368020,-5.483552,-3.434580,-1.979492,-2.022152,-0.937069,0.002662,-2.381591
15521,HVSA_0_1,-463.573730,69.182426,-18.914116,22.859167,0.735867,-7.253482,-7.202471,-5.319007,-5.854908,...,-7.792398,-9.402816,-6.964743,-5.560274,-5.928011,-6.585182,-5.301041,-4.754488,-5.721908,-8.970046
15599,HVSA_0_10,-452.379944,58.461617,-26.529619,10.806691,1.040473,-11.684329,-15.975926,-17.110899,-8.533467,...,-5.176428,-3.543585,-4.472883,-2.353557,1.883047,-0.825696,-3.325481,2.212896,-4.497185,-7.248011
15621,HVSA_0_100,-454.134918,85.565826,-16.623894,23.212719,-7.808586,-7.204660,-8.445378,-17.406126,-16.752789,...,-4.534226,-5.633986,-0.189009,-2.829734,-5.591987,-2.570790,-4.265398,-1.526478,-1.496358,-6.113244
15631,HVSA_0_101,-419.757965,73.650085,-20.263416,30.691788,-5.919299,-15.747584,-17.799961,-13.380462,-10.132165,...,-4.724228,-6.154249,-2.757484,-4.379042,-3.424964,-2.619114,-3.643760,1.918766,-5.222338,-9.505955
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7334,WomenWhoStutter_9_5,-331.060883,8.423851,-32.912979,25.618399,-23.380960,2.367096,-14.927188,-5.307941,0.028746,...,1.926433,-2.305741,1.709073,0.266926,2.327720,-2.078656,-2.214721,-1.796524,1.960576,0.512515
7339,WomenWhoStutter_9_6,-287.171539,24.612055,11.593957,-2.373049,-19.041893,1.381284,-8.410904,-6.094374,-21.232731,...,1.157626,1.489891,-1.526303,-4.642986,-2.262572,-2.588369,2.589427,-5.378926,0.691114,-3.360295
7357,WomenWhoStutter_9_7,-284.419769,69.935936,4.447401,25.512430,-23.518784,-3.872571,2.403355,-14.279772,-22.612999,...,1.685291,-3.814619,1.026565,-3.971704,1.371947,1.164272,2.777372,-0.703542,-1.983613,-1.159616
7340,WomenWhoStutter_9_8,-359.677887,48.367851,14.129713,3.370583,-19.779791,1.081605,-1.616947,-4.654747,-21.594097,...,4.271441,1.339565,-1.568165,-2.710129,1.628097,-2.416452,2.993908,0.311044,-1.634658,-3.653098
7344,WomenWhoStutter_9_9,-308.420288,43.304848,4.558290,25.408195,-5.581814,-15.347582,-3.209874,-7.895386,-15.488366,...,1.119454,3.923148,-0.920379,-0.061525,1.307001,-3.842120,-0.719028,-5.158088,-0.348154,-4.080893

In [16]:
df['Name'] = df[df.columns[0:3]].apply(
    lambda x: '_'.join(x.dropna().astype(str)),
    axis=1
)
df.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,WordRep,DifficultToUnderstand,Interjection,NoStutteredWords,NaturalPause,Music,NoSpeech,Name
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,0,0,0,3,1,0,0,HeStutters_0_0
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,0,0,0,3,1,0,0,HeStutters_0_1
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,0,0,0,3,0,0,0,HeStutters_0_2
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,0,0,0,2,0,0,0,HeStutters_0_3
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,0,0,0,3,0,0,0,HeStutters_0_4

In [17]:
df_final = pd.merge(df, df_features, how='inner', on='Name')
df_final

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,...,-3.795513,-6.413761,-4.393302,-6.851857,-1.345678,-2.414483,-0.139190,-3.250939,-1.076688,-3.112857
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,...,-2.320607,-2.304815,0.727050,-3.252625,-0.454332,-5.220855,1.762970,1.637708,5.408992,3.000758
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,...,-2.084867,0.856960,-0.589489,-0.935007,0.202947,-2.603561,-1.701218,-2.591237,0.655423,0.828504
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21851,WomenWhoStutter,109,35,25793600,25841600,0,0,0,0,0,...,-0.212379,-2.497097,0.301876,-0.940992,1.480227,-3.224166,-0.283757,-1.745628,-0.291208,-2.122259
21852,WomenWhoStutter,109,36,26168480,26216480,0,0,1,1,3,...,0.469681,0.946680,3.426248,2.854356,3.438966,1.599130,-0.027652,-0.536464,0.672164,0.099344
21853,WomenWhoStutter,109,37,3569440,3617440,0,0,0,0,0,...,2.552520,1.043865,5.112990,2.753652,6.350295,4.314575,4.543754,2.557735,3.055340,1.963480
21854,WomenWhoStutter,109,38,28479840,28527840,0,0,1,0,0,...,-2.183299,-2.654434,0.102920,0.218169,3.987160,4.052852,3.327593,1.931874,1.226030,-0.934264
21855,WomenWhoStutter,109,39,29318080,29366080,0,0,0,0,0,...,4.607246,-0.500197,3.647939,-4.066661,1.693356,-3.745692,5.492465,2.733986,3.008399,-0.880915

In [18]:
df_final.iloc[0]

Show                         HeStutters
EpId                                  0
ClipId                                0
Start                          31900320
Stop                           31948320
Unsure                                0
PoorAudioQuality                      0
Prolongation                          0
Block                                 0
SoundRep                              0
WordRep                               0
DifficultToUnderstand                 0
Interjection                          0
NoStutteredWords                      3
NaturalPause                          1
Music                                 0
NoSpeech                              0
Name                     HeStutters_0_0
0                           -392.172791
1                             63.350689
2                              4.833431
3                              6.977844
4                               2.16969
5                             -3.574424
6                             -7.091357
7                             -1.978344
8                             -8.984579
9                             -4.724132
10                            -3.345275
11                            -6.573854
12                            -7.026947
13                            -0.745677
14                            -5.378401
15                            -2.588643
16                             -3.69619
17                            -2.479981
18                             -5.27147
19                            -1.902793
20                            -4.386556
21                            -3.504835
22                            -4.280024
23                            -3.954014
24                            -2.094274
25                            -2.712759
26                            -3.411031
27                            -3.436019
28                            -3.972343
29                            -3.795513
30                            -6.413761
31                            -4.393302
32                            -6.851857
33                            -1.345678
34                            -2.414483
35                             -0.13919
36                            -3.250939
37                            -1.076688
38                            -3.112857
Name: 0, dtype: object

In [19]:
df_final.head()

,Show,EpId,ClipId,Start,Stop,Unsure,PoorAudioQuality,Prolongation,Block,SoundRep,...,29,30,31,32,33,34,35,36,37,38
0,HeStutters,0,0,31900320,31948320,0,0,0,0,0,...,-3.795513,-6.413761,-4.393302,-6.851857,-1.345678,-2.414483,-0.139190,-3.250939,-1.076688,-3.112857
1,HeStutters,0,1,31977120,32025120,0,0,0,0,0,...,-2.320607,-2.304815,0.727050,-3.252625,-0.454332,-5.220855,1.762970,1.637708,5.408992,3.000758
2,HeStutters,0,2,34809760,34857760,0,0,0,0,0,...,-3.249218,-3.218731,0.360520,-0.115838,1.723229,-1.460772,-1.430723,-1.429669,-0.178196,-3.046811
3,HeStutters,0,3,35200640,35248640,0,0,1,0,0,...,-2.084867,0.856960,-0.589489,-0.935007,0.202947,-2.603561,-1.701218,-2.591237,0.655423,0.828504
4,HeStutters,0,4,35721920,35769920,0,0,0,0,0,...,-2.057481,-3.225782,-1.561315,-3.723942,-2.249673,-3.513439,-2.097951,-1.940040,0.020210,-0.556461

In [20]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21856 entries, 0 to 21855
Data columns (total 57 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Show                   21856 non-null  object
 1   EpId                   21856 non-null  int64
 2   ClipId                 21856 non-null  int64
 3   Start                  21856 non-null  int64
 4   Stop                   21856 non-null  int64
 5   Unsure                 21856 non-null  int64
 6   PoorAudioQuality       21856 non-null  int64
 7   Prolongation           21856 non-null  int64
 8   Block                  21856 non-null  int64
 9   SoundRep               21856 non-null  int64
 10  WordRep                21856 non-null  int64
 11  DifficultToUnderstand  21856 non-null  int64
 12  Interjection           21856 non-null  int64
 13  NoStutteredWords       21856 non-null  int64
 14  NaturalPause           21856 non-null  int64
 15  Music                  21856 non-null  int64
 16  NoSpeech               21856 non-null  int64
 17  Name                   21856 non-null  object
 18  0                      21856 non-null  float32
 19  1                      21856 non-null  float32
 20  2                      21856 non-null  float32
 21  3                      21856 non-null  float32
 22  4                      21856 non-null  float32
 23  5                      21856 non-null  float32
 24  6                      21856 non-null  float32
 25  7                      21856 non-null  float32
 26  8                      21856 non-null  float32
 27  9                      21856 non-null  float32
 28  10                     21856 non-null  float32
 29  11                     21856 non-null  float32
 30  12                     21856 non-null  float32
 31  13                     21856 non-null  float32
 32  14                     21856 non-null  float32
 33  15                     21856 non-null  float32
 34  16                     21856 non-null  float32
 35  17                     21856 non-null  float32
 36  18                     21856 non-null  float32
 37  19                     21856 non-null  float32
 38  20                     21856 non-null  float32
 39  21                     21856 non-null  float32
 40  22                     21856 non-null  float32
 41  23                     21856 non-null  float32
 42  24                     21856 non-null  float32
 43  25                     21856 non-null  float32
 44  26                     21856 non-null  float32
 45  27                     21856 non-null  float32
 46  28                     21856 non-null  float32
 47  29                     21856 non-null  float32
 48  30                     21856 non-null  float32
 49  31                     21856 non-null  float32
 50  32                     21856 non-null  float32
 51  33                     21856 non-null  float32
 52  34                     21856 non-null  float32
 53  35                     21856 non-null  float32
 54  36                     21856 non-null  float32
 55  37                     21856 non-null  float32
 56  38                     21856 non-null  float32
dtypes: float32(39), int64(16), object(2)
memory usage: 6.3+ MB

In [21]:
df_final = df_final[df_final.PoorAudioQuality == 0]
df_final = df_final[df_final.DifficultToUnderstand == 0]
df_final = df_final[df_final.Music == 0]
df_final = df_final[df_final.NoSpeech == 0]
df_final = df_final[df_final.Unsure == 0]

In [22]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16292 entries, 0 to 21855
Data columns (total 57 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Show                   16292 non-null  object
 1   EpId                   16292 non-null  int64
 2   ClipId                 16292 non-null  int64
 3   Start                  16292 non-null  int64
 4   Stop                   16292 non-null  int64
 5   Unsure                 16292 non-null  int64
 6   PoorAudioQuality       16292 non-null  int64
 7   Prolongation           16292 non-null  int64
 8   Block                  16292 non-null  int64
 9   SoundRep               16292 non-null  int64
 10  WordRep                16292 non-null  int64
 11  DifficultToUnderstand  16292 non-null  int64
 12  Interjection           16292 non-null  int64
 13  NoStutteredWords       16292 non-null  int64
 14  NaturalPause           16292 non-null  int64
 15  Music                  16292 non-null  int64
 16  NoSpeech               16292 non-null  int64
 17  Name                   16292 non-null  object
 18  0                      16292 non-null  float32
 19  1                      16292 non-null  float32
 20  2                      16292 non-null  float32
 21  3                      16292 non-null  float32
 22  4                      16292 non-null  float32
 23  5                      16292 non-null  float32
 24  6                      16292 non-null  float32
 25  7                      16292 non-null  float32
 26  8                      16292 non-null  float32
 27  9                      16292 non-null  float32
 28  10                     16292 non-null  float32
 29  11                     16292 non-null  float32
 30  12                     16292 non-null  float32
 31  13                     16292 non-null  float32
 32  14                     16292 non-null  float32
 33  15                     16292 non-null  float32
 34  16                     16292 non-null  float32
 35  17                     16292 non-null  float32
 36  18                     16292 non-null  float32
 37  19                     16292 non-null  float32
 38  20                     16292 non-null  float32
 39  21                     16292 non-null  float32
 40  22                     16292 non-null  float32
 41  23                     16292 non-null  float32
 42  24                     16292 non-null  float32
 43  25                     16292 non-null  float32
 44  26                     16292 non-null  float32
 45  27                     16292 non-null  float32
 46  28                     16292 non-null  float32
 47  29                     16292 non-null  float32
 48  30                     16292 non-null  float32
 49  31                     16292 non-null  float32
 50  32                     16292 non-null  float32
 51  33                     16292 non-null  float32
 52  34                     16292 non-null  float32
 53  35                     16292 non-null  float32
 54  36                     16292 non-null  float32
 55  37                     16292 non-null  float32
 56  38                     16292 non-null  float32
dtypes: float32(39), int64(16), object(2)
memory usage: 4.8+ MB

In [23]:
df_final.to_csv("sep28k-mfcc.csv",index=False)